user_num = int(input('Enter integer:\n'))
print("You entered:", user_num)
print(user_num, "squared is", (user_num * user_num))
print("And", user_num, "cubed is", (user_num * user_num * user_num), "!!")
user_numTwo = int(input('Enter another integer:\n'))
print("4 +", user_numTwo, "is", (4+user_numTwo))
print("4 *", user_numTwo, "is", (4*user_numTwo))
